pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('publish') {
            steps {
                echo 'happy helming'
            }
        }
        stage('workingdirectory') {
            steps {
                sh 'mkdir workingdirectory'
            }
        }
        stage('create_file') {
            steps {
                sh 'touch workingdirectory/DevOps'
            }
        }
        stage('Write_to_file') {
            steps {
                sh 'echo "I love pipeline" > workingdirectory/DevOps'
            }
        }
        stage('Install_terraform') {
            steps {
                script {
                    // Set GNUPGHOME and GPG_TTY environment variables
                    def gnupgHome = '/tmp/gnupg_home'
                    sh "mkdir -p ${gnupgHome}"
                    sh "chmod 700 ${gnupgHome}" // Set appropriate permissions
                    env.GNUPGHOME = gnupgHome
                    env.GPG_TTY = '/dev/tty'

                    // Download HashiCorp GPG key and import it
                    sh '''
                        wget -q -O hashicorp-archive-keyring.gpg https://apt.releases.hashicorp.com/gpg
                        gpg --batch --dearmor -o hashicorp-archive-keyring.gpg < hashicorp-archive-keyring.gpg
                        sudo mv hashicorp-archive-keyring.gpg /usr/share/keyrings/
                    '''
                    
                    // Add HashiCorp apt repository
                    sh '''
                        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
                        sudo apt update
                        sudo apt install -y terraform
                    '''
                }
            }
        }
        stage('terraform_version') {
            steps {
                sh 'terraform -version'
            }
        }
        
    }
}
