pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('publish') {
            steps {
                echo 'happy helming'
            }
        }
        stage('workingdirectory') {
            steps {
                sh 'mkdir workingdirectory'
            }
        }
        stage('create_file') {
            steps {
                sh 'touch workingdirectory/DevOps'
            }
        }
        stage('Write_to_file') {
            steps {
                sh 'echo "I love pipeline" > workingdirectory/DevOps'
            }
        }
        stage('Install_terraform') {
            steps {
                sh '''
                    wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o hashicorp-archive-keyring.gpg
                    echo "deb [signed-by=hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
                    sudo mv hashicorp-archive-keyring.gpg /usr/share/keyrings/
                    sudo apt update
                    sudo apt install -y terraform
                '''
            }
        }

        stage('terraform_version') {
            steps {
                sh 'terraform -version'
            }
        }
        
    }
}
